name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - name: Set connection string
      env: 
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      run: heroku config:set MongoConnection__ServerName=$MONGO_CONNECTION_STRING -a blue-plague
    - name: Set smtp password
      env:
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: heroku config:set SmtpServer__SmtpPassword=$SMTP_PASSWORD -a blue-plague
    - name: Push container
      run: heroku container:push web -a blue-plague
    - name: Release container
      run: heroku container:release web -a blue-plague
