name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        APP_NAME: ${{ 'blue-plague' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku config:set MongoConnection__ServerName=$MONGO_CONNECTION_STRING -a $APP_NAME
        heroku config:set SmtpServer__SmtpPassword=$SMTP_PASSWORD -a $APP_NAME
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
